daysUntilStale: 7
daysUntilClose: 7
exemptLabels:
  - bug
  - enhancement
  - renovate
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.

  该 issue 在近期内缺少更新或答复，如果仍然缺少更新或响应，issue 将被关闭。
